- name: mysql configuration
  hosts: mysql
  become: yes
  vars:
    mysql_root_password: ExpenseApp@1
    login_host: mysql.daws-81s.online
  tasks:
  - name: ansible to install mysql server
    ansible.builtin.package: 
      name: mysql-server
      state: present

  - name: start and enable mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes

  - name: connect to mysql server
    community.mysql.mysql_info:
      login_user: root   
      login_password: "{{ mysql_root_password }}"
      login_host: "{{ login_host }}"
    ignore_errors: true
    register: mysql_info

  - name: print the output
    ansible.builtin.debug:
      msg: "{{ mysql_info }}"
